#ifndef FIR_ZU4EV_HW_H
#define FIR_ZU4EV_HW_H

#include <stdint.h>
#include "xparameters.h"

#define FIR_CTRL_BASEADDR      0xA0000000U

#define FIR_REG_CONTROL        0x00U
#define FIR_REG_ARCH_ID        0x04U
#define FIR_REG_SAMPLE_COUNT   0x08U
#define FIR_REG_STATUS         0x0CU
#define FIR_REG_CYCLE_COUNT    0x10U
#define FIR_REG_MISMATCH_COUNT 0x14U
#define FIR_REG_DEBUG_SEEN     0x18U
#define FIR_REG_DEBUG_EMITTED  0x1CU
#define FIR_REG_DEBUG_SVALID   0x20U
#define FIR_REG_DEBUG_SREADY   0x24U

#define FIR_CTRL_START_MASK       0x00000001U
#define FIR_CTRL_SOFT_RESET_MASK  0x00000002U

#define FIR_STATUS_DONE_MASK      0x00000001U
#define FIR_STATUS_BUSY_MASK      0x00000002U
#define FIR_STATUS_ERROR_MASK     0x00000004U

#define FIR_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID

#if defined(XPAR_PSU_DDR_0_S_AXI_BASEADDR)
#define FIR_DDR_BASEADDR XPAR_PSU_DDR_0_S_AXI_BASEADDR
#elif defined(XPAR_PSU_DDR_0_BASEADDRESS)
#define FIR_DDR_BASEADDR XPAR_PSU_DDR_0_BASEADDRESS
#else
#define FIR_DDR_BASEADDR 0x00000000U
#endif

#define FIR_TX_BUFFER_BASE (FIR_DDR_BASEADDR + 0x01000000U)
#define FIR_RX_BUFFER_BASE (FIR_DDR_BASEADDR + 0x02000000U)

#define FIR_UART_CONSOLE "COM9"

#endif
