function T = sweep_orders(spec)
%SWEEP_ORDERS Generate FIR candidates for baseline and final-spec groups.

groups = { ...
    struct('name', 'baseline_taps100', 'orders', spec.baseline_taps - 1), ...
    struct('name', 'baseline_order100', 'orders', spec.baseline_order), ...
    struct('name', 'final_spec', 'orders', []) ...
    };

methods = cellstr(spec.design_methods);
ap_targets = spec.ap_targets_db(:).';
rows = {};
row_idx = 1;

for g = 1:numel(groups)
    group = groups{g};
    for m = 1:numel(methods)
        method = methods{m};
        for ap_idx = 1:numel(ap_targets)
            ap_target = ap_targets(ap_idx);
            [dp, ds] = db_to_dev(ap_target, spec.ast_min_db);
            stop_weight = max(dp / ds, 1.0);
            order_list = local_order_list(group.name, group.orders, spec, dp, ds);
            for order = order_list
                try
                    b = design_filter_backend(order, method, spec, stop_weight, ap_target, spec.ast_min_db);
                    metrics = evaluate_fir_metrics(b, spec);
                    rows(row_idx, :) = local_pack_row(group.name, method, order, ap_target, stop_weight, b, metrics, spec); %#ok<AGROW>
                    row_idx = row_idx + 1;
                catch err
                    warning('Design failed for %s / %s / order %d: %s', group.name, method, order, err.message);
                end
            end
        end
    end
end

function order_list = local_order_list(group_name, fixed_orders, spec, dp, ds)
if ~isempty(fixed_orders)
    order_list = fixed_orders;
    return;
end

delta_w = (spec.ws - spec.wp) * pi;
n_est = ceil((spec.ast_min_db - 8) / (2.285 * delta_w));
lower = max(100, 2 * floor(max(n_est - 40, 100) / 2));
upper = min(520, 2 * ceil((n_est + 40) / 2));
coarse = 100:20:520;
local = lower:4:upper;
order_list = unique([coarse local]);
if strcmp(group_name, 'final_spec')
    order_list = order_list(order_list >= 100);
end
end

T = cell2table(rows, 'VariableNames', local_variable_names());
end

function row = local_pack_row(group_name, method, order, ap_target, stop_weight, b, metrics, spec)
taps = numel(b);
row = { ...
    sprintf('%s__%s__n%d__ap%.3f', group_name, method, order, ap_target), ...
    group_name, ...
    method, ...
    order, ...
    taps, ...
    ap_target, ...
    stop_weight, ...
    metrics.ap_db, ...
    metrics.passband_min_db, ...
    metrics.passband_max_db, ...
    metrics.ast_db, ...
    metrics.transition_width, ...
    metrics.group_delay_samples, ...
    mod(taps, 2) == 1, ...
    (metrics.ast_db >= spec.design_selection.ast_min_db) && ...
    (metrics.ap_db <= spec.design_selection.ap_max_db), ...
    string(strjoin(compose('%.18g', b(:).'), ',')) ...
    };
end

function names = local_variable_names()
names = { ...
    'design_id', ...
    'design_group', ...
    'method', ...
    'order', ...
    'taps', ...
    'ap_target_db', ...
    'stop_weight', ...
    'ap_db', ...
    'passband_min_db', ...
    'passband_max_db', ...
    'ast_db', ...
    'transition_width', ...
    'group_delay_samples', ...
    'odd_length', ...
    'meets_spec', ...
    'coeff_csv' ...
    };
end
