function T = sweep_weights(spec)
%SWEEP_WEIGHTS Sweep stopband weights for the two baseline interpretations.

weight_scales = [0.25 0.5 1 2 4 8 16];
baseline_defs = { ...
    struct('name', 'baseline_taps100', 'order', spec.baseline_taps - 1), ...
    struct('name', 'baseline_order100', 'order', spec.baseline_order) ...
    };

methods = {'firpm', 'firls'};
rows = {};
row_idx = 1;

for bidx = 1:numel(baseline_defs)
    baseline = baseline_defs{bidx};
    for midx = 1:numel(methods)
        method = methods{midx};
        for ap_idx = 1:numel(spec.ap_targets_db)
            ap_target = spec.ap_targets_db(ap_idx);
            [dp, ds] = db_to_dev(ap_target, spec.ast_min_db);
            nominal_weight = max(dp / ds, 1.0);
            for scale = weight_scales
                stop_weight = nominal_weight * scale;
                try
                    b = design_filter_backend(baseline.order, method, spec, stop_weight, ap_target, spec.ast_min_db);
                    metrics = evaluate_fir_metrics(b, spec);
                    rows(row_idx, :) = { ...
                        sprintf('%s__%s__w%.3f__ap%.3f', baseline.name, method, stop_weight, ap_target), ...
                        baseline.name, ...
                        method, ...
                        baseline.order, ...
                        numel(b), ...
                        ap_target, ...
                        stop_weight, ...
                        scale, ...
                        metrics.ap_db, ...
                        metrics.ast_db, ...
                        string(strjoin(compose('%.18g', b(:).'), ',')) ...
                        }; %#ok<AGROW>
                    row_idx = row_idx + 1;
                catch err
                    warning('Weight sweep failed for %s / %s / scale %.3f: %s', baseline.name, method, scale, err.message);
                end
            end
        end
    end
end

T = cell2table(rows, 'VariableNames', { ...
    'design_id', 'design_group', 'method', 'order', 'taps', 'ap_target_db', ...
    'stop_weight', 'weight_scale', 'ap_db', 'ast_db', 'coeff_csv'});
end
